version: "3.7"
services:
    app:
        build:
            args:
                user: mesrs
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: courier
        container_name: courier-app
        depends_on:
            - db
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - courier
    db:
        image: mysql:8.0
        container_name: courier-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - courier
    nginx:
        image: nginx:1.17-alpine
        container_name: courier-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - courier
networks:
    courier:
        driver: bridge
